// NSL C Transpilation Backend Implementation

#include "codegen.hpp"
#include <sstream>
#include <cassert>
#include <algorithm>

namespace nsl {

// ──────────────────────────────────────────────────────────────────────────
// Constructor
// ──────────────────────────────────────────────────────────────────────────
CCodeGen::CCodeGen(DiagnosticEngine& diag) : m_diag(diag) {}

// ──────────────────────────────────────────────────────────────────────────
// Formatting helpers
// ──────────────────────────────────────────────────────────────────────────
void CCodeGen::indent() {
    for (int i = 0; i < m_indent; ++i) m_out << "    ";
}

void CCodeGen::line(const std::string& s) {
    indent();
    m_out << s << "\n";
}

void CCodeGen::line() {
    m_out << "\n";
}

std::string CCodeGen::fresh(const std::string& prefix) {
    return "__nsl_" + prefix + "_" + std::to_string(m_tmpCounter++);
}

// ──────────────────────────────────────────────────────────────────────────
// Type name mapping: NSL → C
// ──────────────────────────────────────────────────────────────────────────
std::string CCodeGen::cTypeName(const std::string& nslType) {
    if (nslType == "int"    || nslType == "i32" || nslType == "i64") return "int64_t";
    if (nslType == "float"  || nslType == "f32") return "float";
    if (nslType == "double" || nslType == "f64") return "double";
    if (nslType == "bool")   return "int";
    if (nslType == "char")   return "char";
    if (nslType == "string") return "const char*";
    if (nslType == "void")   return "void";
    if (nslType == "null")   return "void*";
    if (nslType == "byte"  || nslType == "u8") return "uint8_t";
    if (nslType == "size")   return "size_t";
    // Generic parameterized types in string form: ptr<X>, ref<X>, array<X>
    if (nslType.rfind("ptr<", 0) == 0)   return nslType.substr(4, nslType.size()-5) + "*";
    if (nslType.rfind("ref<", 0) == 0)   return nslType.substr(4, nslType.size()-5) + "*";
    if (nslType.rfind("array<", 0) == 0) return "NSLArray";
    return nslType; // user-defined struct name
}

std::string CCodeGen::cTypeName(const TypeExpr& te) {
    if (te.name == "int"    || te.name == "i32" || te.name == "i64") return "int64_t";
    if (te.name == "float"  || te.name == "f32") return "float";
    if (te.name == "double" || te.name == "f64") return "double";
    if (te.name == "bool")   return "int";
    if (te.name == "char")   return "char";
    if (te.name == "string") return "const char*";
    if (te.name == "void")   return "void";
    if (te.name == "null")   return "void*";
    if (te.name == "byte" || te.name == "u8") return "uint8_t";
    if (te.name == "size")   return "size_t";

    if ((te.name == "ptr" || te.isPtr) && !te.params.empty())
        return cTypeName(te.params[0]) + "*";
    if ((te.name == "ref" || te.isRef) && !te.params.empty())
        return cTypeName(te.params[0]) + "*";
    if (te.name == "array" && !te.params.empty())
        return "NSLArray"; // generic array struct
    return te.name; // user-defined struct
}

std::string CCodeGen::cTypeName(const TypePtr& t) {
    if (!t) return "void";
    return cTypeName(t->toString());
}

// ──────────────────────────────────────────────────────────────────────────
// Expression emission
// ──────────────────────────────────────────────────────────────────────────
std::string CCodeGen::emitExpr(Expr& e) {
    m_lastExpr = "";
    e.accept(*this);
    return m_lastExpr;
}

std::string CCodeGen::emitExprStr(Expr* e) {
    if (!e) return "0";
    return emitExpr(*e);
}

// ──────────────────────────────────────────────────────────────────────────
// Statement helpers
// ──────────────────────────────────────────────────────────────────────────
void CCodeGen::emitStmt(Stmt& s) { s.accept(*this); }

void CCodeGen::emitStmts(std::vector<StmtPtr>& stmts) {
    for (auto& s : stmts) if (s) emitStmt(*s);
}

void CCodeGen::emitBlock(std::vector<StmtPtr>& stmts) {
    line("{");
    ++m_indent;
    emitStmts(stmts);
    --m_indent;
    line("}");
}

// ──────────────────────────────────────────────────────────────────────────
// Runtime header
// ──────────────────────────────────────────────────────────────────────────
void CCodeGen::emitRuntimeHeader() {
    m_out << "/* Generated by NSL Compiler (nslc) - Native Systems Language */\n";
    m_out << "/* DO NOT EDIT - This file is auto-generated. */\n\n";
    m_out << "#include <stdint.h>\n";
    m_out << "#include <stddef.h>\n";
    m_out << "#include <stdbool.h>\n";
    m_out << "#include <stdlib.h>\n";
    m_out << "#include <string.h>\n";
    m_out << "#include <stdio.h>\n";
    m_out << "#include <setjmp.h>\n";
    m_out << "\n";
    m_out << "/* NSL Runtime Types */\n";
    m_out << "typedef struct { void* data; size_t len; size_t cap; } NSLArray;\n";
    m_out << "typedef struct { void* data; size_t size; } NSLArena;\n";
    m_out << "typedef struct { void* data; size_t size; } NSLZone;\n";
    m_out << "\n";
    m_out << "/* NSL Runtime Functions */\n";
    m_out << "static inline NSLArray nsl_make_array(void* data, size_t len) {\n";
    m_out << "    NSLArray a; a.data = data; a.len = len; a.cap = len; return a;\n";
    m_out << "}\n";
    m_out << "static inline size_t nsl_len(NSLArray a) { return a.len; }\n";
    m_out << "static inline void* nsl_index(NSLArray a, size_t i) {\n";
    m_out << "    return (char*)a.data + i; /* element access - size depends on T */\n";
    m_out << "}\n";
    m_out << "\n";
    m_out << "/* NSL Arena allocator */\n";
    m_out << "static inline NSLArena nsl_arena_create(size_t size) {\n";
    m_out << "    NSLArena a; a.data = malloc(size); a.size = size; return a;\n";
    m_out << "}\n";
    m_out << "static inline void* nsl_arena_alloc(NSLArena* a, size_t sz) {\n";
    m_out << "    (void)a; return malloc(sz); /* simplified arena */\n";
    m_out << "}\n";
    m_out << "static inline void nsl_arena_free(NSLArena* a) {\n";
    m_out << "    free(a->data); a->data = NULL; a->size = 0;\n";
    m_out << "}\n";
    m_out << "\n";
    m_out << "/* NSL Zone allocator */\n";
    m_out << "static inline NSLZone nsl_zone_create(size_t size) {\n";
    m_out << "    NSLZone z; z.data = malloc(size); z.size = size; return z;\n";
    m_out << "}\n";
    m_out << "static inline void* nsl_zone_alloc(NSLZone* z, size_t sz) {\n";
    m_out << "    (void)z; return malloc(sz); /* simplified zone */\n";
    m_out << "}\n";
    m_out << "static inline void nsl_zone_free(NSLZone* z) {\n";
    m_out << "    free(z->data); z->data = NULL; z->size = 0;\n";
    m_out << "}\n";
    m_out << "\n";
    m_out << "/* NSL exception simulation */\n";
    m_out << "typedef struct { int code; const char* msg; } NSLException;\n";
    m_out << "static jmp_buf __nsl_jmp_buf;\n";
    m_out << "static NSLException __nsl_current_exception;\n";
    m_out << "#define NSL_TRY  if (setjmp(__nsl_jmp_buf) == 0)\n";
    m_out << "#define NSL_CATCH else\n";
    m_out << "#define NSL_THROW(msg) do { __nsl_current_exception.msg = (msg); longjmp(__nsl_jmp_buf, 1); } while(0)\n";
    m_out << "\n";
}

// ──────────────────────────────────────────────────────────────────────────
// Module bindings for 'use' declarations
// ──────────────────────────────────────────────────────────────────────────
void CCodeGen::emitModuleBindings() {
    // io module
    if (m_imports.count("io")) {
        m_out << "/* io module bindings */\n";
        m_out << "static inline void io_print(const char* s) { printf(\"%s\\n\", s); }\n";
        m_out << "static inline void io_print_int(int64_t n) { printf(\"%\" PRId64 \"\\n\", n); }\n";
        m_out << "static inline void io_print_float(double f) { printf(\"%g\\n\", f); }\n";
        m_out << "static inline void io_print_bool(int b) { printf(\"%s\\n\", b ? \"true\" : \"false\"); }\n";
        m_out << "static inline const char* io_read_line(void) {\n";
        m_out << "    static char buf[4096]; fgets(buf, sizeof(buf), stdin); return buf;\n";
        m_out << "}\n\n";
    }
    // math module
    if (m_imports.count("math")) {
        m_out << "#include <math.h>\n";
        m_out << "/* math module bindings */\n";
        m_out << "static inline int64_t math_add(int64_t a, int64_t b) { return a + b; }\n";
        m_out << "static inline int64_t math_sub(int64_t a, int64_t b) { return a - b; }\n";
        m_out << "static inline int64_t math_mul(int64_t a, int64_t b) { return a * b; }\n";
        m_out << "static inline int64_t math_div(int64_t a, int64_t b) { return b ? a / b : 0; }\n";
        m_out << "static inline double  math_sqrt(double x) { return sqrt(x); }\n";
        m_out << "static inline double  math_pow(double a, double b) { return pow(a, b); }\n";
        m_out << "static inline double  math_abs(double x) { return fabs(x); }\n\n";
    }
    // bits module
    if (m_imports.count("bits")) {
        m_out << "/* bits module bindings */\n";
        m_out << "static inline int64_t bits_shift_left(int64_t x, int n)  { return x << n; }\n";
        m_out << "static inline int64_t bits_shift_right(int64_t x, int n) { return x >> n; }\n";
        m_out << "static inline int64_t bits_and(int64_t a, int64_t b) { return a & b; }\n";
        m_out << "static inline int64_t bits_or(int64_t a, int64_t b)  { return a | b; }\n";
        m_out << "static inline int64_t bits_xor(int64_t a, int64_t b) { return a ^ b; }\n\n";
    }
    // mem module
    if (m_imports.count("mem")) {
        m_out << "/* mem module bindings */\n";
        m_out << "static inline void mem_copy(void* dst, const void* src, size_t sz) { memcpy(dst, src, sz); }\n";
        m_out << "static inline void mem_set(void* dst, int val, size_t sz) { memset(dst, val, sz); }\n\n";
    }
    // sys module
    if (m_imports.count("sys")) {
        m_out << "/* sys module bindings */\n";
        m_out << "static inline int64_t sys_call(int64_t id, void* args) {\n";
        m_out << "    (void)id; (void)args; return 0; /* platform syscall stub */\n";
        m_out << "}\n\n";
    }
    // simd module (stubs – real impl would use intrinsics)
    if (m_imports.count("simd")) {
        m_out << "/* simd module bindings (portable stubs) */\n";
        m_out << "typedef struct { float x, y, z, w; } SIMD4;\n";
        m_out << "static inline SIMD4 simd_pack4(float a,float b,float c,float d) {\n";
        m_out << "    SIMD4 v; v.x=a; v.y=b; v.z=c; v.w=d; return v;\n";
        m_out << "}\n";
        m_out << "static inline SIMD4 simd_add4(SIMD4 a, SIMD4 b) {\n";
        m_out << "    SIMD4 v; v.x=a.x+b.x; v.y=a.y+b.y; v.z=a.z+b.z; v.w=a.w+b.w; return v;\n";
        m_out << "}\n\n";
    }
    // net module
    if (m_imports.count("net") || m_imports.count("network")) {
        m_out << "/* net module stub */\n";
        m_out << "typedef struct { int fd; } NSLSocket;\n\n";
    }
    // graphics module
    if (m_imports.count("graphics")) {
        m_out << "/* graphics module stub */\n\n";
    }
    // audio module
    if (m_imports.count("audio")) {
        m_out << "/* audio module stub */\n\n";
    }
}

// ──────────────────────────────────────────────────────────────────────────
// Top-level generate
// ──────────────────────────────────────────────────────────────────────────
std::string CCodeGen::generate(Program& prog) {
    // First pass: collect imports
    for (auto& d : prog.decls) {
        if (auto* u = dynamic_cast<UseDecl*>(d.get())) {
            std::string modName;
            if (!u->modulePath.empty()) modName = u->modulePath[0];
            else                        modName = u->name;
            m_imports.insert(modName);
        }
    }

    emitRuntimeHeader();

    // Need inttypes.h for PRId64
    m_out << "#include <inttypes.h>\n\n";

    emitModuleBindings();

    // Emit type declarations (forward declarations first)
    for (auto& d : prog.decls) {
        if (auto* td = dynamic_cast<TypeDecl*>(d.get())) {
            m_decls << "typedef struct " << td->name << " " << td->name << ";\n";
        }
    }
    if (!m_decls.str().empty()) {
        m_out << "/* Type forward declarations */\n" << m_decls.str() << "\n";
    }

    // Emit type definitions
    for (auto& d : prog.decls) {
        if (auto* td = dynamic_cast<TypeDecl*>(d.get())) {
            visitTypeDecl(*td);
        }
    }

    // Emit const declarations
    for (auto& d : prog.decls) {
        if (auto* cd = dynamic_cast<ConstDecl*>(d.get())) {
            visitConstDecl(*cd);
        }
    }

    // Emit function forward declarations
    m_out << "/* Function forward declarations */\n";
    for (auto& d : prog.decls) {
        if (auto* fn = dynamic_cast<FunctionDecl*>(d.get())) {
            std::string retType = cTypeName(fn->returnType);
            m_out << retType << " " << fn->name << "(";
            for (std::size_t i = 0; i < fn->params.size(); ++i) {
                if (i) m_out << ", ";
                m_out << cTypeName(fn->params[i].typeAnnotation) << " " << fn->params[i].name;
            }
            m_out << ");\n";
        }
    }
    m_out << "\n";

    // Emit function bodies
    for (auto& d : prog.decls) {
        if (auto* fn = dynamic_cast<FunctionDecl*>(d.get())) {
            visitFunctionDecl(*fn);
        }
    }

    return m_out.str();
}

// ──────────────────────────────────────────────────────────────────────────
// Declarations
// ──────────────────────────────────────────────────────────────────────────
void CCodeGen::visitProgram(Program& n) {
    // Not used directly – generate() handles the program.
}

void CCodeGen::visitUseDecl(UseDecl& n) { /* handled in generate() */ }

void CCodeGen::visitExportDecl(ExportDecl& n) {
    // In C, exports are just non-static functions/variables.
    line("/* export " + n.symbol + " */");
}

void CCodeGen::visitContextDecl(ContextDecl& n) {
    line("/* context " + n.contextName + " */");
}

void CCodeGen::visitMacroDecl(MacroDecl& n) {
    line("/* macro " + n.name + " */");
    // Macros expand to static inline functions
    line("static inline void __nsl_macro_" + n.name + "(void) {");
    ++m_indent;
    emitStmts(n.body);
    --m_indent;
    line("}");
    line();
}

void CCodeGen::visitTypeDecl(TypeDecl& n) {
    m_out << "struct " << n.name << " {\n";
    for (auto& f : n.fields) {
        m_out << "    " << cTypeName(f.typeAnnotation) << " " << f.name << ";\n";
    }
    m_out << "};\n\n";

    // Emit method implementations
    for (auto& m : n.methods) {
        if (!m) continue;
        std::string retType = cTypeName(m->returnType);
        m_out << retType << " " << n.name << "__" << m->name << "("
              << n.name << "* self";
        for (auto& p : m->params) {
            m_out << ", " << cTypeName(p.typeAnnotation) << " " << p.name;
        }
        m_out << ") ";
        m_out << "{\n";
        ++m_indent;
        emitStmts(m->body);
        --m_indent;
        m_out << "}\n\n";
    }
}

void CCodeGen::visitConstDecl(ConstDecl& n) {
    std::string t = cTypeName(n.typeAnnotation);
    std::string v = n.init ? emitExpr(*n.init) : "0";
    m_out << "static const " << t << " " << n.name << " = " << v << ";\n";
}

void CCodeGen::visitFunctionDecl(FunctionDecl& n) {
    std::string retType = cTypeName(n.returnType);
    m_out << retType << " " << n.name << "(";
    for (std::size_t i = 0; i < n.params.size(); ++i) {
        if (i) m_out << ", ";
        m_out << cTypeName(n.params[i].typeAnnotation) << " " << n.params[i].name;
    }
    m_out << ") {\n";
    ++m_indent;
    emitStmts(n.body);
    // Implicit return 0 for main / void for others
    if (n.returnType.name == "int" && n.name == "main") {
        // Already handled by explicit return in most programs
    }
    --m_indent;
    m_out << "}\n\n";
}

// ──────────────────────────────────────────────────────────────────────────
// Statements
// ──────────────────────────────────────────────────────────────────────────
void CCodeGen::visitLetDecl(LetDecl& n) {
    std::string typeName;
    if (n.typeAnnotation) typeName = cTypeName(*n.typeAnnotation);
    else if (n.init)      typeName = "auto"; // will fix via init type
    else                  typeName = "void*";

    // Determine actual C type from init expression type if needed
    if (typeName == "auto" && n.init) {
        typeName = "int64_t"; // default inferred type for ints; sema would have filled this
        if (auto* sl = dynamic_cast<StringLitExpr*>(n.init.get()))  typeName = "const char*";
        if (auto* il = dynamic_cast<IntLitExpr*>(n.init.get()))     typeName = "int64_t";
        if (auto* fl = dynamic_cast<FloatLitExpr*>(n.init.get()))   typeName = "double";
        if (auto* bl = dynamic_cast<BoolLitExpr*>(n.init.get()))    typeName = "int";
        if (auto* ne = dynamic_cast<NewExpr*>(n.init.get()))
            typeName = cTypeName(ne->typeExpr) + "*";
        if (!n.init->resolvedType.empty() && n.init->resolvedType != "unknown")
            typeName = cTypeName(n.init->resolvedType);
    }

    // Memory region affects allocation
    switch (n.memSpec.region) {
        case MemRegion::Heap: {
            std::string initExpr = n.init ? emitExpr(*n.init) : "NULL";
            // For new expressions, the init already includes malloc
            if (!n.typeAnnotation && !n.init) {
                indent(); m_out << typeName << "* " << n.name << " = NULL;\n";
            } else {
                // Determine inner type for heap alloc
                std::string inner = n.typeAnnotation
                    ? cTypeName(*n.typeAnnotation)
                    : typeName;
                indent();
                m_out << inner << "* " << n.name << " = " << initExpr << ";\n";
            }
            return;
        }
        case MemRegion::Stack: {
            std::string inner = n.typeAnnotation ? cTypeName(*n.typeAnnotation) : typeName;
            std::string initExpr = n.init ? emitExpr(*n.init) : "0";
            indent(); m_out << inner << " " << n.name << " = " << initExpr << ";\n";
            return;
        }
        case MemRegion::Arena: {
            std::string inner = n.typeAnnotation ? cTypeName(*n.typeAnnotation) : typeName;
            std::string initExpr = n.init ? emitExpr(*n.init) : "((" + inner + "*)NULL)";
            indent(); m_out << inner << " " << n.name << " = " << initExpr << ";\n";
            return;
        }
        case MemRegion::Zone: {
            std::string inner = n.typeAnnotation ? cTypeName(*n.typeAnnotation) : typeName;
            std::string initExpr = n.init ? emitExpr(*n.init) : "((" + inner + "*)NULL)";
            indent(); m_out << inner << " " << n.name << " = " << initExpr << ";\n";
            return;
        }
        default: {
            std::string initExpr = n.init ? emitExpr(*n.init) : "";
            indent();
            m_out << typeName << " " << n.name;
            if (!initExpr.empty()) m_out << " = " << initExpr;
            m_out << ";\n";
        }
    }
}

void CCodeGen::visitSetStmt(SetStmt& n) {
    std::string lhs = n.target ? emitExpr(*n.target) : "";
    std::string rhs = n.value  ? emitExpr(*n.value)  : "0";
    indent(); m_out << lhs << " = " << rhs << ";\n";
}

void CCodeGen::visitReturnStmt(ReturnStmt& n) {
    if (n.value) {
        std::string v = emitExpr(*n.value);
        indent(); m_out << "return " << v << ";\n";
    } else {
        indent(); m_out << "return;\n";
    }
}

void CCodeGen::visitBreakStmt(BreakStmt& n) {
    indent(); m_out << "break;\n";
}

void CCodeGen::visitContinueStmt(ContinueStmt& n) {
    indent(); m_out << "continue;\n";
}

void CCodeGen::visitFreeStmt(FreeStmt& n) {
    std::string v = n.ptr ? emitExpr(*n.ptr) : "NULL";
    indent(); m_out << "free(" << v << ");\n";
}

void CCodeGen::visitThrowStmt(ThrowStmt& n) {
    if (n.value) {
        std::string v = emitExpr(*n.value);
        indent(); m_out << "NSL_THROW(\"\" /* " << v << " */);\n";
    } else {
        indent(); m_out << "NSL_THROW(\"\");\n";
    }
}

void CCodeGen::visitIfStmt(IfStmt& n) {
    std::string cond = n.condition ? emitExpr(*n.condition) : "0";
    indent(); m_out << "if (" << cond << ") {\n";
    ++m_indent;
    emitStmts(n.thenBlock);
    --m_indent;
    if (n.elseIf) {
        indent(); m_out << "} else ";
        visitIfStmt(*n.elseIf);
        return;
    } else if (!n.elseBlock.empty()) {
        indent(); m_out << "} else {\n";
        ++m_indent;
        emitStmts(n.elseBlock);
        --m_indent;
    }
    indent(); m_out << "}\n";
}

void CCodeGen::visitMatchStmt(MatchStmt& n) {
    std::string subj = n.subject ? emitExpr(*n.subject) : "0";
    bool first = true;
    for (auto& mc : n.cases) {
        if (!mc.pattern) {
            // default
            if (!first) { indent(); m_out << "} else {\n"; }
            else        { indent(); m_out << "{\n"; }
            first = false;
        } else {
            std::string pat = emitExpr(*mc.pattern);
            if (first) {
                indent(); m_out << "if ((" << subj << ") == (" << pat << ")) {\n";
                first = false;
            } else {
                indent(); m_out << "} else if ((" << subj << ") == (" << pat << ")) {\n";
            }
        }
        ++m_indent;
        emitStmts(mc.body);
        --m_indent;
    }
    if (!first) { indent(); m_out << "}\n"; }
}

void CCodeGen::visitForStmt(ForStmt& n) {
    // for <var> in <iterable>
    // We generate: for (size_t __i = 0; __i < <iter>.len; __i++) { T <var> = ...; ... }
    std::string iterVar = fresh("iter");
    std::string idxVar  = fresh("i");
    std::string iterable = n.iterable ? emitExpr(*n.iterable) : "0";

    indent(); m_out << "{ NSLArray " << iterVar << " = " << iterable << ";\n";
    ++m_indent;
    indent(); m_out << "for (size_t " << idxVar << " = 0; "
                    << idxVar << " < " << iterVar << ".len; "
                    << "++" << idxVar << ") {\n";
    ++m_indent;
    // Declare the iteration variable
    indent(); m_out << "void* " << n.iterVar << " = nsl_index(" << iterVar << ", " << idxVar << ");\n";
    emitStmts(n.body);
    --m_indent;
    indent(); m_out << "}\n";
    --m_indent;
    indent(); m_out << "}\n";
}

void CCodeGen::visitWhileStmt(WhileStmt& n) {
    std::string cond = n.condition ? emitExpr(*n.condition) : "0";
    indent(); m_out << "while (" << cond << ") {\n";
    ++m_indent;
    emitStmts(n.body);
    --m_indent;
    indent(); m_out << "}\n";
}

void CCodeGen::visitLoopStmt(LoopStmt& n) {
    indent(); m_out << "for (;;) {\n";
    ++m_indent;
    emitStmts(n.body);
    --m_indent;
    indent(); m_out << "}\n";
}

void CCodeGen::visitTryCatchStmt(TryCatchStmt& n) {
    indent(); m_out << "NSL_TRY {\n";
    ++m_indent;
    emitStmts(n.tryBlock);
    --m_indent;
    indent(); m_out << "} NSL_CATCH {\n";
    ++m_indent;
    if (n.catchVar) {
        std::string ct = n.catchType ? cTypeName(*n.catchType) : "NSLException";
        indent(); m_out << ct << " " << *n.catchVar << " = __nsl_current_exception;\n";
    }
    emitStmts(n.catchBlock);
    --m_indent;
    indent(); m_out << "}\n";
}

void CCodeGen::visitExprStmt(ExprStmt& n) {
    if (!n.expr) return;
    std::string e = emitExpr(*n.expr);
    indent(); m_out << e << ";\n";
}

// ──────────────────────────────────────────────────────────────────────────
// Expression visitors – each stores result in m_lastExpr
// ──────────────────────────────────────────────────────────────────────────
void CCodeGen::visitIdentExpr(IdentExpr& n) {
    m_lastExpr = n.id;
}

void CCodeGen::visitIntLitExpr(IntLitExpr& n) {
    m_lastExpr = std::to_string(n.value) + "LL";
}

void CCodeGen::visitFloatLitExpr(FloatLitExpr& n) {
    // Use ostringstream for clean float representation
    std::ostringstream os; os << n.value;
    m_lastExpr = os.str();
}

void CCodeGen::visitStringLitExpr(StringLitExpr& n) {
    // Re-escape the string for C
    std::string s = "\"";
    for (char c : n.value) {
        switch (c) {
            case '\n': s += "\\n"; break;
            case '\t': s += "\\t"; break;
            case '\r': s += "\\r"; break;
            case '"':  s += "\\\""; break;
            case '\\': s += "\\\\"; break;
            default:   s += c;
        }
    }
    s += "\"";
    m_lastExpr = s;
}

void CCodeGen::visitCharLitExpr(CharLitExpr& n) {
    std::string s = "'";
    switch (n.value) {
        case '\n': s += "\\n"; break;
        case '\t': s += "\\t"; break;
        case '\'': s += "\\'"; break;
        case '\\': s += "\\\\"; break;
        default:   s += n.value;
    }
    s += "'";
    m_lastExpr = s;
}

void CCodeGen::visitBoolLitExpr(BoolLitExpr& n) {
    m_lastExpr = n.value ? "1" : "0";
}

void CCodeGen::visitNullLitExpr(NullLitExpr& n) {
    m_lastExpr = "NULL";
}

void CCodeGen::visitBinaryExpr(BinaryExpr& n) {
    std::string lhs = n.lhs ? emitExpr(*n.lhs) : "0";
    std::string rhs = n.rhs ? emitExpr(*n.rhs) : "0";
    std::string op  = n.op;
    // Map NSL operators to C operators
    if (op == "and") op = "&&";
    else if (op == "or") op = "||";
    else if (op == "is") op = "==";
    m_lastExpr = "(" + lhs + " " + op + " " + rhs + ")";
}

void CCodeGen::visitUnaryExpr(UnaryExpr& n) {
    std::string operand = n.operand ? emitExpr(*n.operand) : "0";
    if (n.op == "not") m_lastExpr = "(!" + operand + ")";
    else               m_lastExpr = "(" + n.op + operand + ")";
}

void CCodeGen::visitCallExpr(CallExpr& n) {
    // Build argument list
    std::string args;
    for (std::size_t i = 0; i < n.args.size(); ++i) {
        if (i) args += ", ";
        if (n.args[i]) args += emitExpr(*n.args[i]);
    }

    // Build callee string
    std::string callee;
    if (auto* id = dynamic_cast<IdentExpr*>(n.callee.get())) {
        callee = id->id;
    } else if (auto* mem = dynamic_cast<MemberExpr*>(n.callee.get())) {
        std::string obj = emitExpr(*mem->object);
        // Map "module.function" to "module_function" in C
        callee = obj + "_" + mem->member;
    } else {
        callee = n.callee ? emitExpr(*n.callee) : "__unknown";
    }

    m_lastExpr = callee + "(" + args + ")";
}

void CCodeGen::visitMemberExpr(MemberExpr& n) {
    std::string obj = n.object ? emitExpr(*n.object) : "";
    // Determine if obj is a pointer type
    m_lastExpr = obj + "." + n.member;
}

void CCodeGen::visitIndexExpr(IndexExpr& n) {
    std::string obj = n.object ? emitExpr(*n.object) : "";
    std::string idx = n.index  ? emitExpr(*n.index)  : "0";
    m_lastExpr = obj + "[" + idx + "]";
}

void CCodeGen::visitNewExpr(NewExpr& n) {
    std::string t = cTypeName(n.typeExpr);
    std::string args;
    for (std::size_t i = 0; i < n.args.size(); ++i) {
        if (i) args += ", ";
        if (n.args[i]) args += emitExpr(*n.args[i]);
    }
    // malloc + optional init
    if (n.args.empty()) {
        m_lastExpr = "((" + t + "*)malloc(sizeof(" + t + ")))";
    } else {
        // Single-argument constructor: treat as sizeof allocation with value
        m_lastExpr = "((" + t + "*)malloc(sizeof(" + t + ")))";
    }
}

void CCodeGen::visitMoveExpr(MoveExpr& n) {
    // In C, move is just the value (ownership is tracked at compiler level)
    m_lastExpr = n.source ? emitExpr(*n.source) : "0";
}

void CCodeGen::visitCopyExpr(CopyExpr& n) {
    // In C, copy is the value (memcpy for structs would need type info)
    m_lastExpr = n.source ? emitExpr(*n.source) : "0";
}

void CCodeGen::visitRefExpr(RefExpr& n) {
    // ref creates a pointer to the source
    std::string src = n.source ? emitExpr(*n.source) : "0";
    m_lastExpr = "(&" + src + ")";
}

void CCodeGen::visitAwaitExpr(AwaitExpr& n) {
    // Await stubs as a direct call in the C backend
    std::string inner = n.expr ? emitExpr(*n.expr) : "0";
    m_lastExpr = "__nsl_await(" + inner + ")";
}

} // namespace nsl
